controller_list:
  - name: fake_arm_controller
    joints:
      - I1_Joint_2
      - T2_Joint_2
      - T3_Joint_2
      - T4_Joint_2
      - I5_Joint_2
  - name: fake_gripper_controller
    joints:
      - G6_finger_joint_l
      - G6_finger_joint_r