arm:
  kinematics_solver: "kdl_kinematics_plugin/KDLKinematicsPlugin #trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin"
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3