<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="climbot_invert">

  <xacro:property name="pi" value="3.1415926535897931" />
  
<!-- materials for visualization -->
  <xacro:include filename="$(find mr_description)/urdf/materials.urdf.xacro" />

  <!-- I Module -->
  <xacro:include filename="$(find mr_description)/urdf/I_module/I_module.urdf.xacro" />

  <!-- T Module -->
  <xacro:include filename="$(find mr_description)/urdf/T_module/T_module.urdf.xacro" />
  
  <!-- I Invert Module -->
  <xacro:include filename="$(find mr_description)/urdf/I_module/I_invert.urdf.xacro" />
  
  <!-- T Invert Module -->
  <xacro:include filename="$(find mr_description)/urdf/T_module/T_invert.urdf.xacro" />

  <!-- Gripper100 Module -->
  <xacro:include filename="$(find mr_description)/urdf/G_module.urdf.xacro" />
    
  <!-- Gripper100 invert Module -->
  <xacro:include filename="$(find mr_description)/urdf/G_invert.urdf.xacro" />
 
  <!-- sleeve_link Module -->
  <xacro:include filename="$(find mr_description)/urdf/sleeve_link.urdf.xacro" />
  
<!-- Now we can start using the macros included above to define the actual robot -->

  <!-- The first use of a macro.  This one was defined in base.urdf.xacro above.
       A macro like this will expand to a set of link and joint definitions, and to additional
       Gazebo-related extensions (sensor plugins, etc).  The macro takes an argument, name, 
       that equals "base", and uses it to generate names for its component links and joints 
       (e.g., base_link).  The included origin block is also an argument to the macro.  By convention, 
       the origin block defines where the component is w.r.t its parent (in this case the parent 
       is the world frame). For more, see http://www.ros.org/wiki/xacro -->



<!--    climbot move group 2-->

  <link name="base_gripper2" />
   
  <xacro:G_invert name="_G6" parent="base_gripper2">
    <origin xyz="0 0 0.17836" rpy="${-pi*0.5} 0 0" />
  </xacro:G_invert>

  <xacro:I_module name="_I5" parent="_G6_palm_link">
    <origin xyz="0 0 0" rpy="${pi*0.5} ${-pi*0.5} 0" />
  </xacro:I_module>

  <xacro:T_invert name="_T4" parent="_I5_Lr_Link_3">
    <origin xyz="0 0 0.005" rpy="0 0 0" />
  </xacro:T_invert>
  
  <xacro:sleeve_link name="sleeve_link" parent="_T4_Lr_Link_0" >
    <origin xyz="0 0 0.005" rpy="0 0 0" />
  </xacro:sleeve_link>
  
  <xacro:T_invert name="_T3" parent="sleeve_link_link">
    <origin xyz="0 0 ${sleeve_link_length+0.005}" rpy="0 0 0" />
  </xacro:T_invert>

  <xacro:T_module name="_T2" parent="_T3_Lr_Link_0">
    <origin xyz="0 0 0.005" rpy="0 0 ${pi}" />
  </xacro:T_module>

  <xacro:I_invert name="_I1" parent="_T2_Lr_Link_3">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:I_invert>
  
  <xacro:G_module name="_G0" parent="_I1_Lr_Link_3">
    <origin xyz="0 0 0" rpy="${pi*0.5} 0 ${-pi*0.5}" />
  </xacro:G_module>
  
</robot>
