name: robot

defaults: #all defaults can be overwritten per node
  eds_pkg: birl_module_canopen
  eds_file: "config/birl_copley.dcf" #Schunk_0_63.dcf"  #CopleyAmp2.eds" 
  
  # the below part of the defaults section is optional
    # canopen_chain_node settings ..
  motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
  motor_layer: #settings passed to motor layer (plugin-specific)
    switching_state: 5 # (Operation_Enable), state for mode switching
  pos_to_device: "rint(rad2deg(pos)*4000)" # rad -> mdeg
  pos_from_device: "deg2rad(obj6064)/4000" # actual position [mdeg] -> rad
  vel_to_device: "rint(rad2deg(vel)*4000)" # rad/s -> mdeg/s
  vel_from_device: "deg2rad(obj606C)/4000" # actual velocity [mdeg/s] -> rad/s
  eff_to_device: "rint(eff)" # just round to integer
  eff_from_device: "0" # unset
  
#  dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
#    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
#    "1017": "100" # heartbeat producer
    
#pos_unit_factor: 1000000.0
#vel_unit_factor: 1000000.0
nodes:
  - name: T_Joint
    id: 3
    #publish: ["1003sub0!"] # For debugging or for simple CANopen interfaces. it blocks the control loop
    #publish: ["6064!"]  #actual position_actual_value
    
#  - name: arm_2_joint
#    id: 4



