joint_limits:
  joint_1:
    has_position_limits: true
    min_position: -2.0
    max_position: 2.0
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 5.0
 
   
